// demos/react/src/App.tsx
import { twMerge } from "tailwind-merge";

function App() {
  return (
    <div className="flex flex-col h-screen items-center justify-center">
      <h1
        className="font-bold text-4xl"
        className:md="text-7xl text-blue-200"
        className:hover="text-red-500"
      >
        React Demo
      </h1>

      <div className={twMerge("mt-12 text-4xl text-red-500")} className:hover="text-blue-500">
        Tailwind Merge
      </div>
    </div>
  );
}

export default App;

// demos/svelte/src/App.svelte
<script lang="ts">
  let pressed = $state(false)
</script>

<div class="flex flex-col h-screen items-center justify-center">
  <h1
    class="font-bold text-4xl"
    class:md="text-7xl text-blue-200"
    class:hover="text-red-500"
  >
    Svelte Demo
  </h1>

  <button
    type="button"
    class="mt-12 text-4xl text-red-500"
    class:hover="text-blue-500"
    class:scale-110={pressed}
    onpointerdown={() => (pressed = true)}
    onpointerup={() => (pressed = false)}
    onpointerleave={() => (pressed = false)}
  >
    Native class directive
  </button>
</div>
